Testing.Web/Models/Home/HomeViewModel.cs
namespace Testing.Web.Models.Home
{
    public class HomeViewModel
    {
    }
}

Testing.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Testing.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Testing.Web/Controllers/RegistrationController.cs
using System.Web.Mvc;
using Testing.Domain;
using Testing.Infrastructure.Persistence;
using Testing.Web.Infrastructure.Mapping;
using Testing.Web.Models.Registration;

namespace Testing.Web.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly IRegistrationTranslator _registrationTranslator;
        private readonly IRepository<Registration> _registrationRepository;
        
        public RegistrationController(
            IRegistrationTranslator registrationTranslator,
            IRepository<Registration> registrationRepository)
        {
            _registrationTranslator = registrationTranslator;
            _registrationRepository = registrationRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var model = new RegistrationViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(RegistrationViewModel model)
        {
            var registration = _registrationTranslator.Translate(model);
            _registrationRepository.Add(registration);

            return RedirectToAction("Confirmation");
        }

        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

Testing.Web/Views/Home/Index.cshtml
@using Testing.Web.Infrastructure.MVC.Sitemap
@{
    ViewBag.Title = PageTitles.Home.Index;
}

<div class="hero-unit">
    <h1>Welcome</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="span4">
        <h2>Home</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
</div>

Testing.Web/Views/Shared/_Layout.cshtml
@using ClientDependency.Core
@using ClientDependency.Core.Mvc
@using Testing.Web.Infrastructure.MVC.Sitemap
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>@PageTitles.Prefix@ViewBag.Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Testing" />
        <meta name="author" content="Testing" />
        
        @{ Html.RequiresCss("bootstrap.css", "Styles", 1)
               .RequiresCss("bootstrap-responsive.css", "Styles", 2)
               .RequiresCss("site.css", "Styles", 3); }
        
        @MvcHtmlString.Create(Html.RenderCssHere(new List<IClientDependencyPath> { new BasicPath("Styles", "~/Content/styles") }))
        
        @RenderSection("Header", false)
        
    </head>
        <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">Testing</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Register", "Index", "Registration")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="container">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; Testing 2012</p>
            </footer>
        </div>
        
		<!--[if lt IE 9]>
            <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
		
        @{ Html.RequiresJs("jquery-1.8.2.js", "Scripts", 1)
               .RequiresJs("jquery.validate.js", "Scripts", 2)
               .RequiresJs("jquery.validate.unobtrusive.js", "Scripts", 3)
               .RequiresJs("bootstrap.js", "Scripts", 4); }

        @RenderSection("Footer", false)

        @MvcHtmlString.Create(Html.RenderJsHere(new List<IClientDependencyPath>
                                                  {
                                                      new BasicPath("Scripts", "~/Scripts"), 
                                                  }))
    </body>
</html>


